### ISSUE TITLE
first pass: create mock interface and classes for infrastructure API

### ISSUE THREAD

**Issue by deepak-swirlds** [hashgraph/full-stack-testing#301]
As part of this task develop a first draft of how the infrastructure API would look like.
It will take time for the infrastructure API to evolve, but this will serve as a draft for review comments by the team.

Deliverables:
 - Mock Interfaces and Classes
 - Class diagrams and sequence diagrams

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/full-stack-testing/issues/382
- [ ] https://github.com/hashgraph/full-stack-testing/issues/447
```

**Comment by nathanklick** [comment]
Closing per changes in requirements.
