### ISSUE TITLE
Charts[Node]: Use latest hedera-explorer release

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#506]
### Feature to Enhance

We need to use latest chart from: https://github.com/hashgraph/hedera-mirror-node-explorer/tree/main/chart

### Requested Enhancement

Currently we store a copy of `hedera-mirror-node-explorer`. We need to check if there is a latest release or not since it appears to throw some errors when loaded from FST deployment

 

### Business Need

We need to be able to view all transactions in the deployed FST network

### Additional Context

![Image](https://github.com/hashgraph/full-stack-testing/assets/811437/190c1065-d254-4529-8f06-d94940828c31)

- [ ] depends on https://github.com/hashgraph/full-stack-testing/issues/675

**Comment by jeromy-cannon** [comment]
Closing, because we are going to remove the sub-chart and deploy externally.
see:
- https://github.com/hashgraph/solo/issues/617
- https://github.com/hashgraph/full-stack-testing/issues/974
