### ISSUE TITLE
CLI: Use Javascript native Kubernetes API Client instead of executing the Kube Control CLI command

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#605]
## Description

FS Network Manager currently invokes the `kubectl` CLI command to perform Kubernetes native cluster operations. This introduces an unmanaged dependency solely under the users control which may result in non deterministic and/or unexpected issues due to versioning/missing executables. 

Therefore, we should switch to using the JavaScript native official Kubernetes API library and make direct K8S API calls. This allows for better error handling, deterministic behavior, and strictly controlled versioning. It also reduces issues related to text based output parsing.

**Comment by leninmehedy** [comment]
We are going to use this library: https://github.com/kubernetes-client/javascript
