### ISSUE TITLE
Charts[Node]: Create new node image to support platform version v0.46 onward

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#701]
### Feature to Enhance

We need to create new node image ubi8-init-java21 for platform version v0.46 onward

### Requested Enhancement

Currently platform v0.46 requires Java21. Therefore, fsnetman is unable to create nodes with the latest platform versions

### Business Need

We need to be able to support latest platform version

### Additional Context

After copying the 0.47.0-alpha.0  into pod, when I tried to start the node, I get error saying:
```
LinkageError occurred while loading main class com.swirlds.platform.Browser
        java.lang.UnsupportedClassVersionError: com/swirlds/platform/Browser has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

**Comment by jeromy-cannon** [comment]
complete
