### ISSUE TITLE
CLI[BUG]: fst-chart-version of 0.19.1 was pulled from cache instead of using 0.20.0 from package.json

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/full-stack-testing#734]
not sure if we want to keep it this way as the helm charts, docker containers, and solo will diverge on versions in the future.  But, I have to manually delete the ~/.solo directory, and also, I don't think there is an option to reset the cache without manually deleting it.

**Comment by leninmehedy** [comment]
`solo init` now reset the cached config. So as long as user is invoking `init` this problem shouldn't occur.
