### ISSUE TITLE
CLI: Cleanup duplicate entries for operator ID and Key

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#763]
There are duplicate entries for operator/treasury account `0.0.2` and key. We should probably eliminate duplicates for consistency: https://github.com/hashgraph/full-stack-testing/blob/main/solo/src/core/constants.mjs#L76-L80

<img width="1404" alt="Screenshot 2024-02-19 at 3 56 29 PM" src="https://github.com/hashgraph/full-stack-testing/assets/811437/ec53d202-f48d-4b9c-bff9-40f757f50ed8">

Need to check which terminology we should use for account `0.0.2`. Should it be `treasury` or `operator`?

Please close this ticket if both terminologies are required.

**Comment by jeromy-cannon** [comment]
The treasury account is a special account fixed as 0.0.2.  And, we want to use the treasury account to fund all of the account key updates so they are no longer defaulted to the genesis key.

The operator is the account we want to use to perform/fund/sign Hedera operations on a wallet or NodeClient.  The operator could be any account, and it can be overridden with environment variables.  They are two separate things.  Both terminologies are required.
