### ISSUE TITLE
Charts[Network]: Remove hardcoded jdwp Java agent

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#883]
## Description

The helm chart forcibly injects the JDWP java agent into the JVM as a hardcoded configuration. Doing so prevents the use of profilers and has a negative performance impact on larger deployments. 

This should not be hardcoded and instead should be injected as needed through configurable `extraEnv` values. 

### Related Issues

- Relates to #884

**Comment by jeromy-cannon** [comment]
fyi @matteriben
